version: 0.2

phases: 
    install:
        runtime-versions:
            python: latest
        commands:
            - echo "installing packages"
    pre_build:
        commands: 
            - echo "we are in the pre build phase"
    build:
        commands:
            - echo "we are in the build block"
            - echo "we will run some tests"
            - sam package  --s3-bucket amebucket-code-sam --template-file template.yaml --output-template-file generated-template.yaml
            - sam deploy --template-file generated-template.yaml --stack-name hello-world-sam --capabilities CAPABILITY_IAM
            - aws lambda publish-version --function-name hello-world-sam-helloworldpython3-eCctm6k1s9j5
    post_build:
        commands:
            - echo "we are in the post build phase, you can create the container here."
artifacts:
   files:
      - generated-template.yaml
      - template.yaml
      - AppSpec.yml
            
