version: 0.2

phases: 
    install:
        runtime-versions:
            python: latest
        commands:
            - echo "installing packages"
    pre_build:
        commands: 
            - echo "we are in the pre build phase"
    build:
        commands:
            - echo "we are in the build block"
            - echo "we will run some tests"
            - sam package  --s3-bucket amebucket-code-sam --template-file template.yaml --output-template-file generated-template.yaml
    post_build:
        commands:
            - echo "we are in the post build phase, you can create the container here."
artifacts:
   files:
      - generated-template.yaml
      - template.yaml
      - Appspec.yml
            
